# Generated by Django 3.0.7 on 2020-07-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=1)),
                ('path', models.CharField(default='1.jpg', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
