# Generated by Django 3.0.5 on 2020-06-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_botkey_botsetup'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUnsavedLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(default='', max_length=64, null=True)),
                ('link', models.URLField(default='')),
            ],
        ),
    ]
