# Generated by Django 3.0.7 on 2020-07-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200706_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botkeylanguage',
            name='lang',
            field=models.CharField(default='', max_length=4, null=True),
        ),
    ]
