"""
Django settings for links project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2i$oqu0zz2j4ih5*rb#4$du=ks0safg^!a$*(f7z_^%arfj$%m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', True)

ALLOWED_HOSTS = ["0.0.0.0", "localhost", "127.0.0.1", "links.cleverapps.io", "10.2.152.143", "hselyc.herokuapp.com",
                 "192.168.1.72"]
HOST = os.getenv('HOST', "http://127.0.0.1:8000")
BOT_HOST = os.getenv('BOT_HOST', "https://hselycbot.herokuapp.com")
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'snowpenguin.django.recaptcha2',
    'account.apps.AccountConfig',
    'api.apps.ApiConfig',
    'app.apps.AppConfig',
    'js_urls',
    'django_extensions',
    'widget_tweaks',
    'social_django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'links.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'links.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
LOGIN_URL = '/account/login/'
DATABASES = {

    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'd7brpffjb0tr1c',
        'USER': 'jlsxjtbguyphii',
        'PASSWORD': '37a803af41f6c6ff0f345016f7e8443031e06cb6a049f4208a279d5e26373925',
        'HOST': 'ec2-52-213-173-172.eu-west-1.compute.amazonaws.com',
        'PORT': '5432',
        'OPTIONS': {'sslmode': 'require'},
    }

}
# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'account.validators.NumberValidator',
    },
    {
        'NAME': 'account.validators.UppercaseValidator',
    },
    {
        'NAME': 'account.validators.LowercaseValidator',
    },
    {
        'NAME': 'account.validators.SymbolValidator',
    }
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'linkitservice@yandex.ru'
EMAIL_HOST_PASSWORD = 'OntolService2020'
DEFAULT_FROM_EMAIL = 'linkitservice@yandex.ru'
EMAIL_USE_TLS = True

AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.vk.VKOAuth2',
    'account.utils.PasswordlessAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
)
SOCIAL_AUTH_URL_NAMESPACE = 'social'
SOCIAL_AUTH_FIELDS_STORED_IN_SESSION = ['local_password', ]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'templates/static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
JS_URLS = (
    'api:search_view',
    'api:index_view',
    'api:account_links',
    'api:account_links_username',
    'api:account_folder',
    'api:account_folder_username',
    'api:account_saved',
    'api:account_saved_username',
    'api:folder_view',
    'api:account_key',
    "api:account_avatar",
    'api:account_rating',
    'link_delete',
    'link_vote',
    'favourite_delete',
    'favourite_save_alt',
    'favourite_save',
    'folder_delete',
    'account:login',
    "account:delete",
    "api:account_new_api_key",
)

RECAPTCHA_PRIVATE_KEY = '6Lf3xa8ZAAAAAPVLUClGyFUd2ONvb0d2TF7anwfs'
RECAPTCHA_PUBLIC_KEY = '6Lf3xa8ZAAAAAMfsWeb0mzmnJQGYN60gn-Rxnh06'
RECAPTCHA_DEFAULT_ACTION = 'generic'
RECAPTCHA_SCORE_THRESHOLD = 0.5
BOT_KEY = "1169232934:AAHFXUE6Fq02RUn0gi7hHrY0KDRm9kx8KDI"
SECURE_SSL_REDIRECT = os.getenv('SSL', False)
if SECURE_SSL_REDIRECT:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

BLACKLIST = ["1xbet", "porn", "nigg", "isis", "игил", "blm", "fuck", "shit", "хуй", "говно", "жопа", "ass",
             "porn", "niger", "1xstavka", "anal", "lenkino", "gangbang", "xvideos", "bongacams"]

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '993780323189-1qu6o9c8jfeqvcsr80qmpdf2q1ik718r.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '8NPdvR4dywuFBXZ5W53XtpX2'
SOCIAL_AUTH_VK_OAUTH2_KEY = '7545690'
SOCIAL_AUTH_VK_OAUTH2_SECRET = 'q5izFVt2Xaf3SFzwwGCv'
SOCIAL_AUTH_VK_OAUTH2_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_KEY = '1669441123224901'
SOCIAL_AUTH_FACEBOOK_SECRET = 'ad86491b3d7ac215d2964894b4205e34'
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_LOGIN_REDIRECT_URL = "/account/view/"
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.social_auth.associate_by_email',  # <--- enable this one
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    'account.utils.social_account_init'
)
SOCIAL_AUTH_DISCONNECT_PIPELINE = (
    'social_core.pipeline.disconnect.get_entries',
    'social_core.pipeline.disconnect.revoke_tokens',
    'social_core.pipeline.disconnect.disconnect',
)
