# Generated by Django 3.0.7 on 2020-06-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='activate',
            new_name='status',
        ),
    ]
